# Generated by Django 4.0.3 on 2022-03-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexPage', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
