# Generated by Django 4.0.3 on 2022-03-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
