# Generated by Django 4.0.3 on 2022-03-23 12:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0067_alter_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', wagtail_color_panel.fields.ColorField(default='#0E3EDA', max_length=7)),
                ('color2', wagtail_color_panel.fields.ColorField(default='#F473B9', max_length=7)),
                ('color3', wagtail_color_panel.fields.ColorField(default='#FFBDE6', max_length=7)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
