# Generated by Django 4.0.3 on 2022-03-19 09:29

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsetting',
            name='color',
            field=wagtail_color_panel.fields.ColorField(default='#000000', max_length=7),
        ),
    ]
