# Generated by Django 4.0.3 on 2022-03-19 13:09

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_alter_colorsetting_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorsetting',
            name='color',
        ),
        migrations.AddField(
            model_name='colorsetting',
            name='color1',
            field=wagtail_color_panel.fields.ColorField(default='#0E3EDA', max_length=7),
        ),
        migrations.AddField(
            model_name='colorsetting',
            name='color2',
            field=wagtail_color_panel.fields.ColorField(default='#F473B9', max_length=7),
        ),
        migrations.AddField(
            model_name='colorsetting',
            name='color3',
            field=wagtail_color_panel.fields.ColorField(default='#FFBDE6', max_length=7),
        ),
    ]
